spring:
  profiles:
    active: local

  thymeleaf:
    cache: false # 타임리프 캐시 끔 -> 개발 시 수정사항 바로 반영?

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: depth1004!
