spring:
  profiles:
    active: local

  devtools:    livereload:      enabled: true
      
  thymeleaf:
    cache: false # 타임리프 캐시 끔 -> 개발 시 수정사항 바로 반영?

  # 메시지 관리 포인트
  messages:
    basename: messages,errors

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/myboard
    username: dev
    password: 1234

  # 세션 유효 (초단위)
  session:
    timeout: 1800

# web.xml의 encodingFilter 부분 대체
server:
  servlet:
    encoding:
      charset: utf-8

# MyBatis설정
mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
